"""
Below is a dict of the final/real destination of all party switchers for the three legislatures between 2008 and 2020.
This was hand-coded because sometimes politicians go through pass-through parties (for a number of internal horse-
trading reasons) in which case it would be false to look at the FIRST party they go to -- often they were there for
only a couple of months.

This hand-coded set uses my knowledge of Romanian parliament to mark the true destination of party switchers.

NB: I only include the code of the FIRST party to which the person switched: if they genuinely switched twice in the
same legislature, I only count the first one (since this ultimately feeds into a single-event hazard model).

NB: for the 2008-2012, "Grupul Deputaților Independenți" was actually the pre-cursor to the UNPR. Granted there were
    further schisms etc. in this group, but the switch was "home --> UNPR." For this legislature genuinely independent
    legislators were called "neafiliați"

NB: There is only one case in which a person leaves the party formally but still caucuses with them: Cosmin Mihai
    POPESCU, in the 2008-2012 legislature.

     CHECK WHY Gheorghe ROMAN 2008-2012 WASN'T MARKED AS A STRAIGHT PDL-PSD SWTICH

NB: for future extensions, note that for whatever reason Siminica Mirea is listed as two separate people for the
    2016-2020 and 2020-2024 legislature
"""

destination_dict = {"2008-2012": {'TĂRÂŢĂ Culiţă': "UNPR",
                                  'BOSTAN Emil': "UNPR",
                                  'IACOB RIDZI Monica Maria': "IND",
                                  'MAZILU Constantin': "UNPR",
                                  'DAVID Gheorghe': "PDL",
                                  'NECULAI Marius': "IND",
                                  'STERIU Valeriu Andrei': "UNPR",
                                  'CHIVU Sorin Serioja': "UNPR",
                                  'AVRAM Marian': "IND",
                                  'BOLDEA Mihail': "UNPR",
                                  'DOBRA Nicolae': "UNPR",
                                  'JIPA Florina Ruxandra': "UNPR",
                                  'DUGULESCU Marius Cristinel': "UNPR",
                                  'IORDACHE Luminiţa': "UNPR",
                                  'DUMITRU Constantin': "PNL",
                                  'IORDĂNESCU Anghel': "UNPR",
                                  'MĂRCUŢIANU Ovidius': "UNPR",
                                  'VASILE Aurelia': "UNPR",
                                  'TABUGAN Ion': "UNPR",
                                  'IRIMESCU Mircea': "PNL",
                                  'CHIRVĂSUŢĂ Laurenţiu': "UNPR",
                                  'MOREGA Dan Ilie': "UNPR",
                                  'PRODAN Tiberiu Aurelian': "PDL",
                                  'GEOANĂ Mircea Dan': "IND",
                                  'NICOLICEA Eugen': "UNPR",
                                  'NEDELCU Vasile': "UNPR",
                                  'CÂMPANU Liviu': "UNPR",
                                  'OAJDEA Daniel Vasile': "IND",
                                  'ŢAGA Claudiu': "UNPR",
                                  'CĂRARE Viorel': "UNPR",
                                  'PIRPILIU Ştefan Daniel': "IND",
                                  'CRĂCIUN Avram': "UNPR",
                                  'DIACONESCU Cristian': "UNPR",
                                  'POPESCU Cosmin Mihai': "IND",
                                  'MARIAN Ovidiu': "PNL",
                                  'ZOICAŞ Gheorghe': "UNPR",
                                  'CIBU Constantin Sever': "UNPR",
                                  'SÂRBU Marian': "UNPR",
                                  'FRUNZULICĂ Doru Claudian': "UNPR",
                                  'GROSU Corneliu': "UNPR",
                                  'ŢUREA Răzvan': "UNPR",
                                  'MIHĂILESCU Petru Şerban': "UNPR",
                                  'BARNA Maria Eugenia': "UNPR",
                                  'NICULESCU MIZIL ŞTEFĂNESCU Oana': "IND",
                                  'SĂNIUŢĂ Marian Florian': "IND",
                                  'TOMA Ion': "UNPR",
                                  'PRIGOANĂ Vasile Silviu': "IND",
                                  'OPREA Gabriel': "UNPR",
                                  'STAVROSITU Maria': "UNPR",
                                  'SOPORAN Vasile Filip': "UNPR",
                                  'ROMAN Gheorghe': "PSD"},
                    "2012-2016": {'DUMITRESCU Florinel': "PSD",
                                  'FENECHIU Cătălin Daniel': "PNL",
                                  'ANGHEL Gabriela Lola': "PNL",
                                  'MARIN Nicolae': "PSD",
                                  'BUTNARU Florinel': "PSD",
                                  'MARCU Nicu': "ALDE",
                                  'CHIŢOIU Daniel': "ALDE",
                                  'MOCANU Victor': "IND",
                                  'TARARACHE Mihai': "IND",
                                  'COSTE Marius': "PSD",
                                  'PALEOLOGU Theodor': "IND",
                                  'POPA Octavian Marius': "ALDE",
                                  'BUDURESCU Daniel Stamate': "ALDE",
                                  'MANOLACHE Marius': "IND",
                                  'NASTA Nicolae': "ALDE",
                                  'TALOŞ Gheorghe Mirel': "ALDE",
                                  'PĂRAN Dorin': "ALDE",
                                  'EPARU Ion': "IND",
                                  'EHEGARTNER Petru': "ALDE",
                                  'ZGONEA Valeriu Ştefan': "IND",
                                  'GUST BĂLOŞIN Florentin': "IND",
                                  'MIHAI Aurelian': "ALDE",
                                  'GEOANĂ Mircea Dan': "IND",
                                  'NIŢU Remus Daniel': "ALDE",
                                  'BLĂJUŢ Viorel Ionel': "PP DD",
                                  'ZAHARCU Neviser': "IND",
                                  'CALIMENTE Mihăiţă': "ALDE",
                                  'CIOBANU Liliana': "PP DD",
                                  'BĂIŞANU Ştefan Alexandru': "ALDE",
                                  'BECALI George': "IND",
                                  'NICOLAE Alexandri': "ALDE",
                                  'MARIAN Valer': "PP DD",
                                  'CADĂR Leonard': "PSD",
                                  'STURZU Mihai Răzvan': "IND",
                                  'POPESCU Corneliu': "IND",
                                  'GHIŞE Ioan': "IND",
                                  'TOMAC Eugen': "IND",
                                  'POPEANGĂ Vasile': "PNL",
                                  'VOLOSEVICI Andrei Liviu': "IND",
                                  'GEREA Andrei Dominic': "ALDE",
                                  'RĂDULESCU Romeo': "ALDE",
                                  'DRAGOMIR Maria': "IND",
                                  'PELICAN Dumitru': "IND",
                                  'BARBU Daniel Constantin': "ALDE",
                                  'DEACONU Mihai': "IND",
                                  'SAGHIAN Gheorghe': "IND",
                                  'DIACONU Mihai Bogdan': "IND",
                                  'TĂTARU Dan': "IND",
                                  'DRĂGUŞANU Vasile Cătălin': "PNL",
                                  'STOICA Ştefan': "IND",
                                  'STOICA Mihaela': "PSD",
                                  'FRĂTICIU Gheorghe': "IND",
                                  'TOCUŢ Dan Laurenţiu': "ALDE",
                                  'CĂTĂNICIU Steluţa Gustica': "ALDE",
                                  'ARITON Ion': "PNL",
                                  'NEGRUŢ Clement': "IND",
                                  'VOSGANIAN Varujan': "ALDE",
                                  'UDREA Elena Gabriela': "IND",
                                  'IONIŢĂ Dan Aurel': "PSD",
                                  'CALOTĂ Florică Ică': "ALDE",
                                  'PETRESCU Petre': "IND",
                                  'OAJDEA Daniel Vasile': "IND",
                                  'GAVRILESCU Graţiela Leocadia': "ALDE",
                                  'POPESCU TĂRICEANU Călin Constantin Anton': "ALDE",
                                  'TEJU Sorin': "ALDE",
                                  'ENACHE Marian': "IND",
                                  'BOT Octavian': "ALDE",
                                  'BURLACU Ştefan': "UNPR",
                                  'PALAŞCĂ Viorel': "ALDE",
                                  'HARBUZ Liviu': "IND",
                                  'GUNIA Dragoş Ionel': "IND",
                                  'DUMITRU Ovidiu Ioan': "IND",
                                  'GURZĂU Adrian': "IND",
                                  'MOVILĂ Petru': "IND",
                                  'POPESCU Florin Aurelian': "IND",
                                  'COMŞA Cornel George': "IND",
                                  'SAVU Daniel': "IND",
                                  'AXENTE Ioan': "IND",
                                  'MOCANU Adrian': "IND",
                                  'URSĂRESCU Dorinel': "ALDE",
                                  'KHRAIBANI Camelia': "IND",
                                  'ILIEŞIU Sorin': "PSD",
                                  'POPESCU Dumitru Dian': "ALDE",
                                  },
                    "2016-2020": {'PETREA Gabriel': "PRO",
                                  'BOGACIU Alexandra Corina': "PRO",
                                  'POPA Ion': "ALDE",
                                  'BODEA Marius': "IND",
                                  'SAVIN Emanoil': "PSD",
                                  'GIOANCĂ Eugen': "PNL",
                                  'MELEŞCANU Teodor Viorel': "PSD",
                                  'BURCIU Cristina': "PNL",
                                  'DRĂGHICI Mircea Gheorghe': "IND",
                                  'SIBINESCU Ionuţ': "PSD",
                                  'NIŢĂ Mihai': "PRO",
                                  'MOCIOALCĂ Ion': "PRO",
                                  'CALOTĂ Florică Ică': "PNL",
                                  'GANEA Ion': "PSD",
                                  'POP Georgian': "PRO",
                                  'STANCU Florinel': "PRO",
                                  'MEIROŞU Marilena Emilia': "IND",
                                  'TUDOSE Mihai': "PRO",
                                  'HUNCĂ Mihaela': "PRO",
                                  'BĂDULESCU Dorin Valeriu': "ALDE",
                                  'MARICA Petru Sorin': "PRO",
                                  'NECHIFOR Cătălin Ioan': "IND",
                                  'CÎMPEANU Sorin Mihai': "IND",
                                  'DOBROVIE Matei Adrian': "PNL",
                                  'JIVAN Luminiţa Maria': "IND",
                                  'BOTNARIU Emanuel Gabriel': "IND",
                                  'MIREA Siminica': "PSD",
                                  'BORZA Remus Adrian': "PSD",
                                  'RĂDULESCU Dan Răzvan': "IND",
                                  'IRIZA Scarlat': "PSD",
                                  'TEIŞ Alina': "PRO",
                                  'PODAŞCĂ Gabriela Maria': "IND",
                                  'CUCŞA Marian Gheorghe': "PSD",
                                  'SITTERLI Ovidiu Ioan': "IND",
                                  'ANDREI Alexandru Ioan': "PNL",
                                  'ZAMFIR Daniel Cătălin': "ALDE",
                                  'MOHACI Mihai': "PSD",
                                  'IFTIMIE Neculai': "IND",
                                  'PETCU Toma Florin': "PNL",
                                  'CONSTANTIN Daniel': "IND",
                                  'BIRCHALL Ana': "IND",
                                  'NICOARĂ Marius Petre': "ALDE",
                                  'VĂCARU Alin Vasile': "IND",
                                  'DOBRE Mircea Titus': "IND",
                                  'SURGENT Marius Gheorghe': "PNL",
                                  'PETRIC Octavian': "PRO",
                                  'BĂNICIOIU Nicolae': "IND",
                                  'HĂRĂTĂU Elena': "PNL",
                                  'GĂINĂ Mihăiţă': "PNL",
                                  'PONTA Victor Viorel': "IND",
                                  'COSMA Lavinia Corina': "IND",
                                  'NIŢĂ Ilie': "PSD",
                                  'BANIAS Mircea Marius': "IND",
                                  'HAVRICI Emanuel Iuliu': "PRO",
                                  'DOHOTARU Adrian Octavian': "IND",
                                  'POPA Mihai Valentin': "PRO",
                                  'BÎZGAN GAYRAL Oana Mioara': "IND",
                                  'VLĂDUCĂ Oana Silvia': "PRO",
                                  'TALPOŞ Ioan Iustin': "PSD",
                                  'BĂLĂNESCU Alexandru': "PRO",
                                  'SPÂNU Ion': "PRO",
                                  'PAU Radu Adrian': "PRO",
                                  }
                    }
